### ISSUE TITLE
[FF2] Can You Add More Boss?

### ISSUE THREAD

**Issue by issaralengEZ** [MrTheBank/Maxnus-Network#130]
[FF2] Can You Added Freddy Fazbear Boss?
I Want Play That Boss
First Page: https://forums.alliedmods.net/showthread.php?t=264387
Download: http://www.mediafire.com/download/1r...yf/fazbear.rar

- Request From [TH] issaralengEZ

**Comment by PuShitcake** [comment]
### Freddy Fazbear
A remake edition that don't ask why, because it's should.
(And also your link download that you copy is wrong.)

![freddy-fazbear-remake](https://user-images.githubusercontent.com/63900170/89124077-6933b700-d4fe-11ea-996b-d32ff014f53a.png)

Changes log:
- Change all file location. (to only 1 files instead of many.)
- Change abilities from default to dynamic.
- Add new theme. (less cringe.)
- Remove unneed things.

Download link:
https://www.mediafire.com/file/y03cra7pg664ye9/Freddy+Fazbear+Maxnus-Remake.zip/file

**Comment by issaralengEZ** [comment]
Thank You Very Much Thank You
What's That Boss Is In Pack?

ในวันที่ อา. 2 ส.ค. 2020 20:28 น. PuShitcake <notifications@github.com>
เขียนว่า:
